### PR TITLE
[#13] Add redirect rules

### LINKED ISSUE #13: Define redirection rules
With the move from hosting our own Trac and managing our own VM we now need to look and see what to redirect and where to redirect.

For now, the plan is for the new twistedmatrix.com website to be hosted via this repo and use the GitHub Pages service.

The new website will only provide a very minimal set of functionalities in comparison with Trac.

As a high level the following Trac services are no longer available

* Trac Tickets -> Moved to GitHub Issue - First part done in #11 
* Trac Wiki -> Moved to a GitHub Repo
* Trac Ticket Reports -> Moved to GitHub Issue search URL
* Documentation static files /documentes/ - partly moved to Read The Docs

This ticket is about defining the exact list of URLs that need redirection and decide where to redirect.

### PR DESCRIPTION
**Pull request by ioanacristinamarinescu**
Fixes #13

### CODE REVIEW

**Comment by adiroiban** [comment]
To not forget, we should redirect requests like these to the root page.

 * https://twistedmatrix.com/trac/
 * https://twistedmatrix.com/trac
 * https://twistedmatrix.com/trac/wiki/
 * https://twistedmatrix.com/trac/wiki
 * https://twistedmatrix.com/trac/wiki/WikiStart

And have these extra redirects:

* https://twistedmatrix.com/trac/timeline ->  https://github.com/twisted/twisted/pulse
* https://twistedmatrix.com/trac/roadmap -> https://github.com/twisted/twisted/milestones
* https://twistedmatrix.com/trac/report -> https://github.com/twisted/twisted/issues
* https://twistedmatrix.com/trac/report/* -> https://github.com/twisted/twisted/issues
* https://twistedmatrix.com/trac/newticket -> https://github.com/twisted/twisted/issues/new/choose
* https://twistedmatrix.com/trac/search -> https://github.com/twisted/twisted/issues

**Comment by ioanacristinamarinescu** [comment]
Rules to redirect docs:
https://twistedmatrix.com/documents/14.0.1/api/twisted.internet.task.LoopingCall.html#a
should go to:
https://htmlpreview.github.io/?https://github.com/twisted/documents/blob/main/14.0.1/api/twisted.internet.task.LoopingCall.html#a

**Comment by adiroiban** [comment]
There is no need to do documentation redirection - 

GitHub automatically redirects to the content of this repo https://github.com/twisted/documents

https://github.com/twisted/twisted.github.io/issues/13#issuecomment-1170181200

-----------

So the documents part can be removed

**Review by adiroiban — APPROVED** [review]
Thanks. I think that this is a good start.

We can later refactor or change the way this is done.

But for now I think that this is ready to be merged

**Pull request merged**
